language: php

php:
  - 7.2
  - 7.3
  - 7.4

sudo: false

matrix:
  fast_finish: true

script:
  - vendor/bin/phpunit
  - vendor/bin/phpstan analyse src tests -l max

before_script:
  - composer install
